language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install codecov
    - pip install coverage
    - pip install .

script:
    - coverage run -m unittest discover -s tests

after_success:
    - codecov
