[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
    "hyperopt>=0.2.7",
    "numpy",
    "scikit-learn>=1.2.2",
    "scikit-surprise",
    "rich"
]